### ISSUE TITLE
TypeError: format is not a function

### ISSUE THREAD

**Issue by mkormendy** [alexgorbatchev/gulp-print#28]
Working with:

- Node version 9.8.0
- NPM version 5.7.1
- Gulp CLI version 2.0.1
- Gulp Local version 4.0.0

```javascript
at mapFile (/path-to-project-using-gulp/node_modules/gulp-print/gulp-print.js:18:27)
    at wrappedMapper (/path-to-project-using-gulp/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/path-to-project-using-gulp/node_modules/map-stream/index.js:95:21)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:180:13)
    at Stream.emit (domain.js:439:23)
    at queueData (/path-to-project-using-gulp/node_modules/event-stream/node_modules/map-stream/index.js:43:21)
    at next (/path-to-project-using-gulp/node_modules/event-stream/node_modules/map-stream/index.js:71:7)
    at /path-to-project-using-gulp/node_modules/event-stream/node_modules/map-stream/index.js:85:7
    at /path-to-project-using-gulp/node_modules/gulp-livereload/index.js:45:5
```

Hates this line:

```
const formatted = format(filepath);
```

**Comment by mkormendy** [comment]
There was an error with the way it was called in my code.
